import type { Agent, Land, Listing, Property } from "./types";

import p1 from "@/assets/p1-vila-poljine.jpg";
import p2 from "@/assets/p2-penthouse-bl.jpg";
import p3 from "@/assets/p3-vila-trebinje.jpg";
import p4 from "@/assets/p4-chalet-jahorina.jpg";
import p5 from "@/assets/p5-stan-sarajevo.jpg";
import p6 from "@/assets/p6-vila-neum.jpg";
import z1 from "@/assets/z1-jahorina.jpg";
import z2 from "@/assets/z2-una.jpg";
import z3 from "@/assets/z3-bl-zona.jpg";
import z4 from "@/assets/z4-trebinje.jpg";
import agentImg from "@/assets/agent.jpg";

const agentHadzic: Agent = {
  name: "Mirza Hadžić",
  role: "Senior Partner",
  license: "BiH-RE-0421",
  phone: "+387 33 000 000",
  whatsapp: "+38733000000",
  image: agentImg,
};

const agentKovac: Agent = {
  name: "Lejla Kovač",
  role: "Direktor portfolio",
  license: "BiH-RE-0508",
  phone: "+387 51 000 000",
  whatsapp: "+38751000000",
  image: agentImg,
};

export const properties: Property[] = [
  {
    id: "p1",
    slug: "the-zenith-residence-poljine",
    kind: "property",
    title: "The Zenith Residence",
    subtitle: "Privatna vila sa panoramskim pogledom na Sarajevo",
    region: "Sarajevo - Poljine",
    microLocation: "Poljine, gornja zona",
    transaction: "Prodaja",
    priceEur: 2500000,
    area: 450,
    propertyType: "Vila",
    rooms: 6,
    bathrooms: 5,
    floor: 0,
    totalFloors: 3,
    hasLift: true,
    yearBuilt: 2023,
    heating: "Toplotne pumpe",
    amenities: [
      "Smart Home",
      "Privatni bazen",
      "Sauna / Spa",
      "Privatni lift",
      "Panoramski pogled",
      "Garaža sa EV punjačem",
      "Privatno dvorište",
      "Portir 24/7",
    ],
    buildType: "Armirano-betonska, klasa A+",
    insulation: "Mineralna vuna 18cm, trostruko staklo",
    badge: "Ekskluzivna prodaja",
    featured: true,
    images: [p1, p1, p1],
    description: {
      about:
        "Arhitektonski manifest tihog luksuza na 1.200 metara nadmorske visine. Vila Zenith spaja prefinjeni minimalizam sa toplinom prirodnih materijala — kamen sa Mostarskih kamenoloma, hrastovina i italijanska keramika.",
      interior:
        "Otvoreni dnevni prostor sa 4.5m visine plafona, kuhinja Bulthaup B3, master suite sa privatnim spa-om. Sve sobe imaju izlaz na terasu.",
      location:
        "Smješteno u najekskluzivnijem dijelu Poljina, samo 12 minuta vožnje od centra Sarajeva, a okruženo netaknutom borovom šumom.",
    },
    agent: agentHadzic,
    coordinates: { lat: 43.917, lng: 18.378 },
    distances: [
      { label: "Centar Sarajeva", km: 9 },
      { label: "Aerodrom Sarajevo", km: 18 },
      { label: "Skijalište Bjelašnica", km: 32 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo u ZK",
      energetskiCertifikat: "A+",
    },
  },
  {
    id: "p2",
    slug: "kastel-view-penthouse",
    kind: "property",
    title: "Kastel View Penthouse",
    subtitle: "Penthaus sa terasom od 80m² u srcu Banja Luke",
    region: "Banja Luka - Centar",
    microLocation: "Premium kvart, uz Vrbas",
    transaction: "Prodaja",
    priceEur: 850000,
    area: 240,
    propertyType: "Penthaus",
    rooms: 4,
    bathrooms: 3,
    floor: 12,
    totalFloors: 12,
    hasLift: true,
    yearBuilt: 2024,
    heating: "Podno grijanje",
    amenities: [
      "Smart Home",
      "Privatni lift",
      "Panoramski pogled",
      "Garaža sa EV punjačem",
      "Portir 24/7",
    ],
    buildType: "Novogradnja, klasa A",
    insulation: "Demit fasada 15cm",
    badge: "Novogradnja",
    featured: true,
    images: [p2, p2],
    description: {
      about:
        "Duplex penthaus na vrhu nove kule u banjalučkom Premium kvartu, sa neometanim pogledom na Kastel i tok Vrbasa.",
      interior:
        "Italijanski namještaj Minotti, kuhinja Boffi, integrisan Lutron sistem rasvjete i klime.",
      location: "5 minuta hoda do Gospodske ulice i obale Vrbasa.",
    },
    agent: agentKovac,
    coordinates: { lat: 44.772, lng: 17.191 },
    distances: [
      { label: "Centar Banja Luke", km: 0.4 },
      { label: "Aerodrom Banja Luka", km: 22 },
      { label: "Auto-put E-661", km: 6 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
      energetskiCertifikat: "A",
    },
  },
  {
    id: "p3",
    slug: "vila-kameni-san-trebinje",
    kind: "property",
    title: "Vila Kameni San",
    subtitle: "Restauriran hercegovački posjed sa vinogradom",
    region: "Trebinje",
    microLocation: "Arslanagića most, riverside",
    transaction: "Prodaja",
    priceEur: 940000,
    area: 320,
    propertyType: "Vila",
    rooms: 5,
    bathrooms: 4,
    yearBuilt: 1890,
    totalFloors: 2,
    hasLift: false,
    heating: "Centralno",
    amenities: ["Privatni bazen", "Privatno dvorište", "Sauna / Spa", "Panoramski pogled"],
    buildType: "Originalni hercegovački kamen, restaurirano 2022",
    insulation: "Prirodna izolacija, drvene grede",
    badge: "Provjereno vlasništvo",
    featured: true,
    images: [p3, p3],
    description: {
      about:
        "Imanje iz kasnog 19. vijeka sa kompletno modernizovanim interijerom. Privatni vinograd od 3 dunuma i kamena terasa sa pogledom na Trebišnjicu.",
      interior:
        "Otvoreni concept dnevni boravak sa originalnim kamenom, hrastov pod, custom kuhinja sa Gaggenau aparatima.",
      location: "U srcu vinogorja kod Trebinja, 6 minuta do starog gradskog jezgra.",
    },
    agent: agentHadzic,
    coordinates: { lat: 42.71, lng: 18.343 },
    distances: [
      { label: "Stari grad Trebinje", km: 3 },
      { label: "Dubrovnik aerodrom", km: 35 },
      { label: "Jadransko more (Neum)", km: 90 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo, bez tereta",
      energetskiCertifikat: "B",
    },
  },
  {
    id: "p4",
    slug: "chalet-aurora-jahorina",
    kind: "property",
    title: "Chalet Aurora",
    subtitle: "Ski-in / ski-out planinska rezidencija",
    region: "Jahorina",
    microLocation: "Poljice, uz Olimpijsku stazu",
    transaction: "Prodaja",
    priceEur: 720000,
    area: 185,
    propertyType: "Vila",
    rooms: 4,
    bathrooms: 3,
    yearBuilt: 2022,
    totalFloors: 2,
    hasLift: false,
    heating: "Toplotne pumpe",
    amenities: ["Smart Home", "Sauna / Spa", "Panoramski pogled", "Privatno dvorište"],
    buildType: "Hibridna drvo-čelik konstrukcija",
    insulation: "Pasivna kuća standard",
    badge: "Ekskluzivna prodaja",
    images: [p4, p4],
    description: {
      about:
        "Moderna alpska arhitektura sa direktnim izlazom na ski stazu. Prozori od poda do plafona okrenuti prema padinama Jahorine.",
      interior:
        "Kamin sa centralnom pozicijom, finska sauna, ski room sa custom organizacijom.",
      location: "Direktan ski-in/ski-out pristup, 25 minuta od Sarajeva.",
    },
    agent: agentHadzic,
    coordinates: { lat: 43.74, lng: 18.572 },
    distances: [
      { label: "Centar Sarajeva", km: 30 },
      { label: "Aerodrom Sarajevo", km: 40 },
      { label: "Ski lift", km: 0.1 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
      energetskiCertifikat: "A+",
    },
  },
  {
    id: "p5",
    slug: "stari-grad-residence",
    kind: "property",
    title: "Stari Grad Residence",
    subtitle: "Boutique apartman u srcu Sarajeva",
    region: "Sarajevo - Stari Grad",
    microLocation: "Logavina, kraj Baščaršije",
    transaction: "Prodaja",
    priceEur: 480000,
    area: 145,
    propertyType: "Stan",
    rooms: 3,
    bathrooms: 2,
    floor: 4,
    totalFloors: 5,
    hasLift: true,
    yearBuilt: 2023,
    heating: "Podno grijanje",
    amenities: ["Smart Home", "Privatni lift", "Panoramski pogled", "Portir 24/7"],
    buildType: "Klasa A novogradnja",
    insulation: "Trostruko staklo, demit 12cm",
    badge: "Novogradnja",
    images: [p5, p5],
    description: {
      about:
        "Designer apartman u butik zgradi sa samo 8 jedinica, kombinuje sarajevsku tradiciju i savremeni dizajn.",
      interior:
        "Custom drveni elementi, italijanska keramika, integrisana kuhinja Poliform.",
      location: "Tri minute hoda od Baščaršije, mirna ulica.",
    },
    agent: agentKovac,
    coordinates: { lat: 43.86, lng: 18.43 },
    distances: [
      { label: "Baščaršija", km: 0.3 },
      { label: "Aerodrom Sarajevo", km: 12 },
      { label: "BBI Centar", km: 1.2 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
      energetskiCertifikat: "A",
    },
  },
  {
    id: "p6",
    slug: "villa-mediterraneo-neum",
    kind: "property",
    title: "Villa Mediterraneo",
    subtitle: "Vila na obali Jadrana sa privatnom plažom",
    region: "Neum",
    microLocation: "Brestica, prvi red do mora",
    transaction: "Prodaja",
    priceEur: 1850000,
    area: 380,
    propertyType: "Vila",
    rooms: 5,
    bathrooms: 5,
    yearBuilt: 2021,
    totalFloors: 3,
    hasLift: true,
    heating: "Toplotne pumpe",
    amenities: [
      "Smart Home",
      "Privatni bazen",
      "Sauna / Spa",
      "Privatni lift",
      "Panoramski pogled",
      "Privatno dvorište",
    ],
    buildType: "Mediteran moderna, kameni elementi",
    insulation: "Pasivni standard",
    badge: "Ekskluzivna prodaja",
    images: [p6, p6],
    description: {
      about:
        "Jedina vila na BiH dijelu Jadrana sa privatnim pristupom plaži i infinity bazenom okrenutim prema otvorenom moru.",
      interior:
        "Otvoreni plan, kuhinja Arclinea, master suite sa privatnom terasom i jacuzzijem.",
      location:
        "Prvi red do mora, 5 minuta od centra Neuma, 1 sat od Dubrovnik aerodroma.",
    },
    agent: agentHadzic,
    coordinates: { lat: 42.92, lng: 17.61 },
    distances: [
      { label: "Centar Neum", km: 2 },
      { label: "Dubrovnik aerodrom", km: 65 },
      { label: "Mostar", km: 65 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
      energetskiCertifikat: "A",
    },
  },
];

export const lands: Land[] = [
  {
    id: "z1",
    slug: "olympic-peak-estate-jahorina",
    kind: "land",
    title: "Olympic Peak Estate",
    subtitle: "Građevinska parcela uz olimpijsku ski stazu",
    region: "Jahorina",
    microLocation: "Uz stazu, gornja zona",
    transaction: "Investicioni projekat",
    priceEur: 1800000,
    area: 12000,
    areaDunum: 12,
    landType: "Građevinsko sa dozvolom",
    infrastructure: ["Voda", "Struja", "Asfaltni prilaz", "Optički internet"],
    allowedFloors: "P+2+M",
    occupancyRatio: 0.4,
    slope: "Blagi nagib",
    view: "Planinski pogled",
    permitStatus: "Građevinska dozvola izdana 2024",
    regulationPlan: "U skladu sa Prostornim planom Jahorine 2030",
    badge: "Investicija",
    featured: true,
    images: [z1, z1],
    description: {
      about:
        "Jedinstvena prilika — jedna od posljednjih raspoloživih parcela u prvoj zoni Jahorine sa važećom građevinskom dozvolom za boutique hotel ili rezidencijalni kompleks.",
      location:
        "Direktan pristup ski stazi, 30 minuta od Sarajeva, infrastruktura kompletno izvedena do parcele.",
    },
    agent: agentHadzic,
    coordinates: { lat: 43.745, lng: 18.575 },
    distances: [
      { label: "Ski lift", km: 0.05 },
      { label: "Centar Sarajeva", km: 30 },
      { label: "Aerodrom Sarajevo", km: 40 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo, bez tereta",
    },
  },
  {
    id: "z2",
    slug: "posjed-una-bihac",
    kind: "land",
    title: "Posjed Una",
    subtitle: "Privatno imanje na samoj obali Une",
    region: "Bihać",
    microLocation: "Klokot, uz rijeku Unu",
    transaction: "Prodaja",
    priceEur: 1200000,
    area: 25000,
    areaDunum: 25,
    landType: "Građevinsko u zoni",
    infrastructure: ["Voda", "Struja", "Asfaltni prilaz"],
    allowedFloors: "B+P+1",
    occupancyRatio: 0.25,
    slope: "Blagi nagib",
    view: "Pogled na rijeku",
    permitStatus: "Lokacijski uslovi izdani",
    regulationPlan: "Zona rekreacije i turizma",
    badge: "Provjereno vlasništvo",
    featured: true,
    images: [z2, z2],
    description: {
      about:
        "Imanje na 25.000m² sa 380m izlaza na rijeku Unu. Idealno za eco-luxury rezort ili privatni posjed.",
      location:
        "Netaknuto okruženje Nacionalnog parka Una, 8 minuta od centra Bihaća.",
    },
    agent: agentKovac,
    coordinates: { lat: 44.81, lng: 15.87 },
    distances: [
      { label: "Centar Bihać", km: 7 },
      { label: "Granica HR (Ličko Petrovo Selo)", km: 25 },
      { label: "Zagreb", km: 220 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
    },
  },
  {
    id: "z3",
    slug: "investment-zone-banja-luka",
    kind: "land",
    title: "Investment Zone Aleksandrovac",
    subtitle: "Industrijska zona spremna za razvoj",
    region: "Banja Luka - Slatina",
    microLocation: "Aleksandrovac, uz auto-put",
    transaction: "Investicioni projekat",
    priceEur: 2200000,
    area: 45000,
    areaDunum: 45,
    landType: "Industrijska zona",
    infrastructure: ["Voda", "Struja", "Asfaltni prilaz", "Kanalizacija", "Optički internet"],
    allowedFloors: "P+2",
    occupancyRatio: 0.6,
    slope: "Ravno",
    view: "Pogled na grad",
    permitStatus: "Urbanistička saglasnost",
    regulationPlan: "Regulacioni plan poslovne zone",
    badge: "Investicija",
    images: [z3, z3],
    description: {
      about:
        "Strateška lokacija za logistički centar, proizvodni pogon ili business park. Direktan izlaz na auto-put E-661.",
      location:
        "10 km od centra Banja Luke, 18 km od aerodroma Banja Luka.",
    },
    agent: agentKovac,
    coordinates: { lat: 44.85, lng: 17.30 },
    distances: [
      { label: "Auto-put E-661", km: 0.5 },
      { label: "Aerodrom Banja Luka", km: 18 },
      { label: "Centar Banja Luke", km: 10 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
    },
  },
  {
    id: "z4",
    slug: "vinogorje-trebinje",
    kind: "land",
    title: "Vinogorje Trebinje",
    subtitle: "Posjed sa vinogradom i pogledom na Trebišnjicu",
    region: "Trebinje",
    microLocation: "Popovo polje",
    transaction: "Prodaja",
    priceEur: 680000,
    area: 35000,
    areaDunum: 35,
    landType: "Poljoprivredno",
    infrastructure: ["Voda", "Struja", "Asfaltni prilaz"],
    allowedFloors: "P+1",
    occupancyRatio: 0.15,
    slope: "Padina",
    view: "Pogled na rijeku",
    permitStatus: "Mogućnost prenamjene u građevinsko",
    regulationPlan: "U izradi novog prostornog plana",
    images: [z4, z4],
    description: {
      about:
        "35 dunuma vinograda i maslinjaka u srcu hercegovačkog vinskog regiona. Postojeća kamena kuća za restauraciju.",
      location: "20 minuta od Trebinja, 40 minuta od Dubrovnika.",
    },
    agent: agentHadzic,
    coordinates: { lat: 42.71, lng: 18.10 },
    distances: [
      { label: "Centar Trebinja", km: 22 },
      { label: "Dubrovnik aerodrom", km: 50 },
      { label: "Mostar", km: 100 },
    ],
    legal: {
      vlasnistvo: "1/1",
      uknjizenost: "Uknjiženo",
    },
  },
];

export const allListings: Listing[] = [...properties, ...lands];

export function getListingBySlug(slug: string): Listing | undefined {
  return allListings.find((l) => l.slug === slug);
}
