/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaInvestitoreRouteImport } from './routes/za-investitore'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KatalogIndexRouteImport } from './routes/katalog.index'
import { Route as KatalogSlugRouteImport } from './routes/katalog.$slug'

const ZaInvestitoreRoute = ZaInvestitoreRouteImport.update({
  id: '/za-investitore',
  path: '/za-investitore',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogIndexRoute = KatalogIndexRouteImport.update({
  id: '/katalog/',
  path: '/katalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogSlugRoute = KatalogSlugRouteImport.update({
  id: '/katalog/$slug',
  path: '/katalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o-nama': typeof ONamaRoute
  '/za-investitore': typeof ZaInvestitoreRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o-nama': typeof ONamaRoute
  '/za-investitore': typeof ZaInvestitoreRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog': typeof KatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o-nama': typeof ONamaRoute
  '/za-investitore': typeof ZaInvestitoreRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/o-nama'
    | '/za-investitore'
    | '/katalog/$slug'
    | '/katalog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/o-nama' | '/za-investitore' | '/katalog/$slug' | '/katalog'
  id:
    | '__root__'
    | '/'
    | '/o-nama'
    | '/za-investitore'
    | '/katalog/$slug'
    | '/katalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ONamaRoute: typeof ONamaRoute
  ZaInvestitoreRoute: typeof ZaInvestitoreRoute
  KatalogSlugRoute: typeof KatalogSlugRoute
  KatalogIndexRoute: typeof KatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/za-investitore': {
      id: '/za-investitore'
      path: '/za-investitore'
      fullPath: '/za-investitore'
      preLoaderRoute: typeof ZaInvestitoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/': {
      id: '/katalog/'
      path: '/katalog'
      fullPath: '/katalog/'
      preLoaderRoute: typeof KatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/$slug': {
      id: '/katalog/$slug'
      path: '/katalog/$slug'
      fullPath: '/katalog/$slug'
      preLoaderRoute: typeof KatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ONamaRoute: ONamaRoute,
  ZaInvestitoreRoute: ZaInvestitoreRoute,
  KatalogSlugRoute: KatalogSlugRoute,
  KatalogIndexRoute: KatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
